/**
 * The one generated file in the plugin: the provider table, regenerated by
 * `npm run providers` (which `prepare` runs on install) from the files in
 * src/providers. Dropping a new provider file in and running that script is
 * the complete add-a-provider workflow; the router discovers the rest.
 */
import brave from "./brave.js";
import deepseek from "./deepseek.js";
import duckduckgo from "./duckduckgo.js";
import exa from "./exa.js";
import perplexity from "./perplexity.js";
import searxng from "./searxng.js";
import tavily from "./tavily.js";

/** id → provider descriptor, as a synchronous table. */
export const PROVIDERS = {
  brave,
  deepseek,
  duckduckgo,
  exa,
  perplexity,
  searxng,
  tavily,
};

/** Resolve one provider descriptor by id. */
export const loadProvider = (id) => PROVIDERS[id];
